"""Validate URL freshness check report schema.

The /url-freshness-check skill produces a markdown report with:
- H1 heading: '# URL Freshness Report'
- A '## Summary' section with stats: total checked, OK count, broken count, bot-blocked count
- One or more '## Broken URLs' / '## Redirects' / '## Bot-blocked' subsections (any subset)
- A '## Generated' line with a YYYY-MM-DD date

This is a thin schema check — the report content is generated by the skill, but the
shape must be predictable so downstream tooling (or a future agent reading the report)
can parse it.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from validators._common import cli_main

H1_RE = re.compile(r"^# URL Freshness Report\b", re.MULTILINE)
SUMMARY_RE = re.compile(r"^## Summary\b", re.MULTILINE)
GENERATED_DATE_RE = re.compile(
    r"^(?:## )?Generated:?\s*(?P<date>\d{4}-\d{2}-\d{2})\b", re.MULTILINE
)
STAT_LINE_RE = re.compile(
    r"-\s*(?P<key>total|ok|broken|bot[- ]blocked|redirect)s?\s*[:=]\s*(?P<n>\d+)",
    re.IGNORECASE,
)
REQUIRED_STATS = {"total", "ok", "broken"}


def validate(path: Path) -> list[str]:
    errors: list[str] = []
    if path.is_dir():
        return [f"expected a markdown file, got directory: {path}"]
    text = path.read_text(encoding="utf-8")

    if not H1_RE.search(text):
        errors.append("missing required H1: '# URL Freshness Report'")

    if not SUMMARY_RE.search(text):
        errors.append("missing required '## Summary' section")
    else:
        stats_found = {
            m.group("key").lower().replace(" ", "-").rstrip("s")
            for m in STAT_LINE_RE.finditer(text)
        }
        for required in REQUIRED_STATS:
            if required not in stats_found:
                errors.append(f"summary stats missing '{required}' count")

    if not GENERATED_DATE_RE.search(text):
        errors.append("missing 'Generated: YYYY-MM-DD' line")

    return errors


if __name__ == "__main__":
    sys.exit(cli_main(sys.argv, validate))
