"""Build tests/fixtures/medium_topic_calibration_subset/ from calibration.

Filters calibration to claim_families = {calibration_method, calibration_metric} (22 entries),
producing a self-contained fixture that passes all validators including cross_stage.
This is the v1.1+ schema reference example that mini fixture is too small to
demonstrate (mini has 5 entries; medium has 22 with full optional-field coverage).

Idempotent — re-running rebuilds from current calibration state.
"""
from __future__ import annotations

import re
import shutil
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE = Path.home() / "Claude" / "research-dossiers" / "research_calibration"
OUT = REPO_ROOT / "tests" / "fixtures" / "medium_topic_calibration_subset"
KEEP_FAMILIES = {"calibration_method", "calibration_metric"}


def main() -> int:
    if not SOURCE.is_dir():
        print(f"FATAL: {SOURCE} not found", file=sys.stderr)
        return 2

    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir(parents=True)

    # 1. Filter the bib_ledger to KEEP_FAMILIES.
    src_ledger = (SOURCE / "bib_ledger.yml").read_text(encoding="utf-8")
    data = yaml.safe_load(src_ledger)
    entries = [
        e for e in data["entries"]
        if isinstance(e, dict) and e.get("claim_family") in KEEP_FAMILIES
    ]
    print(f"Filtered {len(entries)} entries from {SOURCE.name}", file=sys.stderr)

    # Preserve ordering; build text manually to keep authors/venue/code_url ordering.
    lines = [
        "# Medium fixture: calibration methods + metrics subset of calibration",
        "# Generated by scripts/build_medium_fixture.py — do not hand-edit.",
        "# 22 entries spanning 2 claim_families with full v1.1 optional-field coverage.",
        "",
        "entries:",
    ]
    keep_arxiv_ids: set[str] = set()
    for e in entries:
        for k in ("bibkey", "primary_url", "title", "status", "claim_family",
                  "authors", "venue", "code_url"):
            if k in e:
                v = e[k]
                if k == "title" and ":" in str(v):
                    lines.append(f"- {k}: '{v}'" if k == "bibkey"
                                 else f"  {k}: '{v}'") if False else None
                v_str = _yaml_scalar(str(v)) if k in ("title", "authors", "venue") else str(v)
                if k == "bibkey":
                    lines.append(f"- {k}: {v_str}")
                else:
                    lines.append(f"  {k}: {v_str}")
        lines.append("")
        m = re.search(r"(\d{4}\.\d{4,5})", e.get("primary_url", ""))
        if m:
            keep_arxiv_ids.add(m.group(1))
    (OUT / "bib_ledger.yml").write_text("\n".join(lines), encoding="utf-8")

    # 2. Build a minimal research_plan.md.
    plan = """# Research Plan: Calibration Methods & Metrics (Medium Fixture)

A scoped subset of calibration covering classical calibration methods and calibration metrics. Used as a v1.1+ schema reference and test fixture (~22 entries). Full calibration covers 6 sub-areas; this fixture covers 2.

## Sub-areas

- A1. Classical calibration methods
  - Source types: arXiv, ICML/NeurIPS/JMLR, classical ML papers
  - Notes: temperature scaling, Platt scaling, isotonic, Beta calibration, histogram binning, vector/matrix scaling.
- A2. Calibration metrics & reliability diagrams
  - Source types: arXiv, AAAI/AISTATS/JMLR
  - Notes: ECE family, Brier score, proper scoring rules, reliability diagrams.
- A3. (Padding) Empirical comparisons
  - Source types: arXiv preprints
  - Notes: cross-cutting empirical evaluations of calibration methods/metrics.
- A4. (Padding) Foundational references
  - Source types: classical statistics, JSTOR
  - Notes: pre-2010 calibration foundations cited as references.

## Out-of-scope

- Conformal prediction (separate sub-area in full calibration)
- Uncertainty quantification (deep ensembles / MC dropout / Bayesian)
- OOD detection
- LLM-specific calibration

## Claim family taxonomy

- calibration_method
- calibration_metric
- comparison_study

## Known landmark papers

- guo2017calibration: temperature scaling, modern NN calibration baseline
- platt1999platt: Platt scaling — sigmoid post-hoc calibration
- naeini2015obtaining: Bayesian binning + ECE family
"""
    (OUT / "research_plan.md").write_text(plan, encoding="utf-8")

    # 3. Copy + filter the dossier file.
    src_dossier_file = SOURCE / "dossier" / "01_calibration_methods_metrics.md"
    if not src_dossier_file.exists():
        print(f"FATAL: {src_dossier_file} not found", file=sys.stderr)
        return 2
    (OUT / "dossier").mkdir()
    shutil.copy(src_dossier_file, OUT / "dossier" / "01_calibration_methods_metrics.md")

    # 4. Copy + filter the agent_index file + build a minimal README.
    src_agent_index_file = (
        Path.home() / "interview_prep_series" / "docs" / "research"
        / "calibration_synthesis" / "01_calibration_methods_metrics.md"
    )
    if not src_agent_index_file.exists():
        print(f"FATAL: {src_agent_index_file} not found", file=sys.stderr)
        return 2
    (OUT / "agent_index").mkdir()
    shutil.copy(
        src_agent_index_file,
        OUT / "agent_index" / "01_calibration_methods_metrics.md",
    )

    # Build minimal README satisfying the agent_index validator.
    readme = """<!-- AGENT-INDEX: medium fixture — calibration methods + metrics subset of calibration. 22 entries. Read this README first. -->

# Calibration Methods & Metrics — Medium Fixture

**Purpose:** v1.1+ schema reference; test fixture for cross_stage validator + dossier-build sub-section logic at ~22-entry scale.
**Scope:** classical calibration methods (temperature scaling, Platt, isotonic, Beta, histogram binning, vector/matrix scaling); calibration metrics (ECE family, Brier, proper scoring rules).
**Coverage:** 22 entries in `01_calibration_methods_metrics.md`.

## ⚠️ Scope boundary

This fixture is a SUBSET of calibration. It covers only calibration methods + metrics. For conformal prediction, uncertainty quantification, OOD detection, and LLM-specific calibration, see the full calibration dossier in interview_prep_series.

## How this is organized

| File | Topic | When to read |
|---|---|---|
| `01_calibration_methods_metrics.md` | classical methods + metrics (anchors A1./A2./...) | Start here |

## Lookup recipes

- **"What's temperature scaling?"** → `01_calibration_methods_metrics.md` § A1
- **"What's ECE?"** → `01_calibration_methods_metrics.md` § A4
- **"How do I get a reliability diagram?"** → `01_calibration_methods_metrics.md` § A4

## Glossary

- **ECE** — Expected Calibration Error: average gap between predicted confidence and accuracy across confidence bins.
- **Reliability diagram** — plot of accuracy vs predicted confidence by bin.
- **Temperature scaling** — single-parameter logit-rescaling calibration.

## Verification & limits

- Citations resolved as of 2026-05-07 (sourced from calibration).
- This fixture is a snapshot subset; do not use as the canonical calibration reference.

## Attribution

Generated by `scripts/build_medium_fixture.py` from `~/Claude/research-dossiers/research_calibration/`.
"""
    (OUT / "agent_index" / "README.md").write_text(readme, encoding="utf-8")

    print(f"Wrote medium fixture to {OUT}", file=sys.stderr)
    return 0


def _yaml_scalar(s: str) -> str:
    if any(c in s for c in [":", "#", "'", '"', "[", "]", "{", "}", ","]):
        escaped = s.replace("'", "''")
        return f"'{escaped}'"
    return s


if __name__ == "__main__":
    sys.exit(main())
